/*
 The JSE trading engine processes a continuous stream of buy and sell orders throughout the trading
 day, each tagged with a timestamp, ticker symbol, order type, quantity, and price. When a listed
 company releases price-sensitive information mid-session, regulators can trigger a trading halt that
 requires all orders placed in the 90 seconds before the halt to be reversed in exact reverse
 chronological order to restore the pre-announcement market state. This is a textbook LIFO problem:
 orders are pushed as they arrive, and when the reversal signal fires, they are popped one by one
 until the stack is empty. Developer Rethabile implements the reversal engine from scratch to prove
 that a stack is the only structure that naturally preserves reverse-order access without sorting,
 indexing, or additional traversal overhead — both push and pop are O(1).
*/

/**
 * Models the JSE trading halt and order-reversal engine using a custom stack built from scratch.
 * Orders stream in during normal trading, then are reversed LIFO on a halt signal.
 */
public class JSEOrderReversalApp {

    /** Identifies whether a trade order is a buy or sell instruction. */
    enum OrderType { BUY, SELL }

    /**
     * Represents one trade order in the pre-halt reversal stack.
     * Holds all fields needed to reconstruct or negate the original market action.
     */
    static class TradeOrderNode {
        String    orderId;
        String    tickerSymbol;
        OrderType orderType;
        int       quantity;
        double    priceRands;
        String    timestampHHMMSS;
        TradeOrderNode orderBeneath; // link toward the bottom of the stack

        /**
         * Creates a trade order node ready to be pushed onto the pre-halt capture stack.
         *
         * @param orderId          unique order reference generated by the exchange gateway
         * @param tickerSymbol     JSE-listed stock ticker, e.g. "NPN", "SOL", "MTN"
         * @param orderType        BUY or SELL
         * @param quantity         number of shares
         * @param priceRands       limit price in South African Rand
         * @param timestampHHMMSS  time the order was received at the matching engine
         */
        TradeOrderNode(String orderId, String tickerSymbol, OrderType orderType,
                       int quantity, double priceRands, String timestampHHMMSS) {
            // Time: O(1) — constant field assignments.
            this.orderId         = orderId;
            this.tickerSymbol    = tickerSymbol;
            this.orderType       = orderType;
            this.quantity        = quantity;
            this.priceRands      = priceRands;
            this.timestampHHMMSS = timestampHHMMSS;
            this.orderBeneath    = null;
        }
    }

    /**
     * Custom LIFO stack that captures trade orders during the 90-second pre-halt window.
     * Implements push, pop, peek, size, isEmpty, and a full reversal sweep.
     */
    static class PreHaltOrderStack {
        private TradeOrderNode stackTop;   // head of internal linked list — newest order
        private int            capturedCount;

        /**
         * Initialises an empty capture stack at the start of each trading window.
         */
        PreHaltOrderStack() {
            // Time: O(1).
            this.stackTop      = null;
            this.capturedCount = 0;
        }

        /**
         * Reports whether the pre-halt window captured no orders.
         *
         * @return true when the stack is empty
         */
        boolean isStackEmpty() {
            // Time: O(1) — single null check.
            return stackTop == null;
        }

        /**
         * Pushes an incoming trade order onto the capture stack as it arrives.
         * LIFO: the newest order is always at the top and will be reversed first.
         *
         * @param orderId          exchange-generated order reference
         * @param tickerSymbol     stock ticker
         * @param orderType        BUY or SELL
         * @param quantity         number of shares
         * @param priceRands       limit price in Rand
         * @param timestampHHMMSS  order arrival time
         */
        void captureOrder(String orderId, String tickerSymbol, OrderType orderType,
                          int quantity, double priceRands, String timestampHHMMSS) {
            // Time: O(1) — two pointer updates; no traversal.
            TradeOrderNode incomingOrder = new TradeOrderNode(
                    orderId, tickerSymbol, orderType, quantity, priceRands, timestampHHMMSS);

            // Push: new order points to previous top, then becomes new top.
            incomingOrder.orderBeneath = stackTop;
            stackTop                   = incomingOrder;
            capturedCount++;

            System.out.println("[CAPTURED] " + timestampHHMMSS + " | " + orderId
                    + " | " + orderType + " " + quantity + " " + tickerSymbol
                    + " @ R" + String.format("%.2f", priceRands));
        }

        /**
         * Peeks at the most recently captured order without removing it.
         * Useful for supervisors reviewing the top of the window before issuing a halt.
         *
         * @return topmost order node, or null if no orders were captured
         */
        TradeOrderNode peekLatestOrder() {
            // Time: O(1) — direct top-pointer read.
            return stackTop;
        }

        /**
         * Pops the most recently captured order from the stack and reverses it.
         * Reversal means: if the original was BUY, the reversal becomes SELL, and vice versa.
         *
         * @return the popped order node, or null if stack is empty
         */
        TradeOrderNode popAndReverseOne() {
            // Time: O(1) — constant pointer update.
            if (isStackEmpty()) {
                return null;
            }

            TradeOrderNode reversedOrder = stackTop;

            // Pop: advance top pointer toward the order beneath.
            stackTop = stackTop.orderBeneath;
            capturedCount--;

            // Derive the reversal direction (LIFO reversal logic).
            OrderType reversalType = (reversedOrder.orderType == OrderType.BUY) ? OrderType.SELL : OrderType.BUY;

            System.out.println("[REVERSED] " + reversedOrder.timestampHHMMSS
                    + " | " + reversedOrder.orderId
                    + " | Original: " + reversedOrder.orderType + " → Reversal: " + reversalType
                    + " | " + reversedOrder.quantity + " " + reversedOrder.tickerSymbol
                    + " @ R" + String.format("%.2f", reversedOrder.priceRands));

            return reversedOrder;
        }

        /**
         * Triggers a full reversal sweep on halt signal, popping every order in LIFO order.
         * Demonstrates that a stack automatically produces the correct reverse chronological sequence.
         */
        void executeHaltReversal() {
            // Time: O(n) — pops n orders, each pop is O(1).
            System.out.println("\n[HALT SIGNAL] Reversing all " + capturedCount
                    + " captured orders in reverse chronological order:");

            // Edge case: halt fires on an empty capture window (no orders in last 90 seconds).
            if (isStackEmpty()) {
                System.out.println("  No orders captured — market state unchanged.");
                return;
            }

            int reversalCount = 0;
            while (!isStackEmpty()) {
                popAndReverseOne();
                reversalCount++;
            }

            System.out.println("[REVERSAL COMPLETE] " + reversalCount
                    + " orders reversed. Market restored to pre-announcement state.");
        }

        /**
         * Traverses the full stack to print the captured window for audit purposes.
         * Uses orderBeneath links — equivalent to singly linked list traversal.
         */
        void printCaptureWindow() {
            // Time: O(n) — visits every node once.
            System.out.println("\n--- Pre-halt Capture Window (newest first) ["
                    + capturedCount + " orders] ---");

            if (isStackEmpty()) {
                System.out.println("  No orders in capture window.");
                return;
            }

            TradeOrderNode cursor = stackTop;
            int rank = 1;
            while (cursor != null) {
                System.out.println("  " + rank + ". " + cursor.timestampHHMMSS
                        + " | " + cursor.orderId + " | " + cursor.orderType
                        + " " + cursor.quantity + " " + cursor.tickerSymbol
                        + " @ R" + String.format("%.2f", cursor.priceRands));
                cursor = cursor.orderBeneath; // traverse downward through the stack
                rank++;
            }
        }

        /**
         * Returns the number of orders currently captured.
         *
         * @return captured order count
         */
        int getCapturedCount() {
            // Time: O(1) — returns stored counter.
            return capturedCount;
        }
    }

    /**
     * Story-driven demo: Rethabile loads a 90-second trading window with orders, inspects the
     * stack, issues a halt, reverses all orders, and tests edge cases throughout.
     *
     * @param args unused command-line arguments
     */
    public static void main(String[] args) {
        // Time: O(n) overall — dominated by the reversal traversal.
        PreHaltOrderStack preHaltStack = new PreHaltOrderStack();

        System.out.println("=== JSE Trading Engine — Pre-Halt Order Reversal System ===");

        // Edge case: halt signal on an empty capture window.
        System.out.println("\n-- Edge case: halt with no captured orders --");
        preHaltStack.executeHaltReversal();

        // Edge case: single order, then undo that one order.
        System.out.println("\n-- Edge case: single order captured --");
        preHaltStack.captureOrder("JSE-00001", "NPN", OrderType.BUY, 500, 3450.00, "10:29:31");
        preHaltStack.printCaptureWindow();
        preHaltStack.executeHaltReversal();

        // Normal scenario: 90-second pre-halt window fills with orders.
        System.out.println("\n-- Normal trading window: orders stream in --");
        preHaltStack.captureOrder("JSE-00002", "SOL",  OrderType.BUY,   200, 680.50, "10:30:01");
        preHaltStack.captureOrder("JSE-00003", "MTN",  OrderType.SELL, 1000, 142.30, "10:30:15");
        preHaltStack.captureOrder("JSE-00004", "AGL",  OrderType.BUY,   350, 560.00, "10:30:22");
        preHaltStack.captureOrder("JSE-00005", "NPN",  OrderType.SELL,  800, 3460.00,"10:30:44");
        preHaltStack.captureOrder("JSE-00006", "SBK",  OrderType.BUY,  1500, 175.40, "10:30:58");

        // Peek — inspect the most recent order without disturbing the stack.
        TradeOrderNode latestOrder = preHaltStack.peekLatestOrder();
        System.out.println("\n[PEEK] Most recent order: " + latestOrder.orderId
                + " — " + latestOrder.orderType + " " + latestOrder.quantity
                + " " + latestOrder.tickerSymbol);

        preHaltStack.printCaptureWindow();

        // Halt announced — reverse all orders in LIFO order.
        System.out.println("\n-- Price-sensitive announcement received; trading halt issued --");
        preHaltStack.executeHaltReversal();

        // Confirm stack is empty and capture count is zero after full reversal.
        System.out.println("\nOrders remaining after reversal: " + preHaltStack.getCapturedCount());
        preHaltStack.printCaptureWindow();
    }
}

/*
 ═══ STUDY NOTES ═══
 Concepts used:
 - LIFO:            Last In, First Out — newest trade order is always reversed first during a halt.
 - push:            captureOrder() records an incoming order on top of the stack in O(1).
 - pop:             popAndReverseOne() retrieves and inverts the most recent order in O(1).
 - peek:            peekLatestOrder() reads the top order without disturbing the stack.
 - call stack:      The JVM's own call stack is LIFO just like this; each method invocation is a push.
 - undo mechanism:  Each reversal undoes one market action — same pattern as a text editor undo.
 - bracket matching:Not directly used here, but the same push-and-pop pattern validates nesting.

 Big-O for every operation:
 - isStackEmpty:       O(1) — one pointer check; constant.
 - captureOrder (push):O(1) — rewires two pointers; no traversal.
 - peekLatestOrder:    O(1) — reads top pointer directly.
 - popAndReverseOne:   O(1) — moves top pointer one step.
 - executeHaltReversal:O(n) — calls pop n times, each O(1).
 - printCaptureWindow: O(n) — visits each node once.
 - getCapturedCount:   O(1) — returns stored integer.
 Space complexity: O(n) — one node per captured order.

 Interview questions this code prepares you for:
 - Why is a stack the natural model for reversing a sequence of events?
 - How does push/pop achieve O(1) time using a linked list?
 - What is the difference between peek and pop?
 - How would you detect whether a reversal is needed (non-empty stack check)?
 - What is the space complexity of a stack-based reversal and why?

 Most common mistake and how this code avoids it:
 - Mistake: Calling pop on an empty stack and receiving a NullPointerException at runtime.
 - Avoided: isStackEmpty() is checked in popAndReverseOne() and executeHaltReversal()
   before any top-pointer access; edge cases print descriptive messages instead of crashing.

 When to use a stack vs the common alternative:
 - Use a stack when the problem requires reverse-order access without sorting: undo systems,
   trading reversals, expression parsers, depth-first search, and function call simulation.
 - Use a queue (FIFO) when order of arrival must be preserved: task schedulers, BFS, event queues.
 - Java built-in comparison: java.util.Stack extends Vector and is thread-safe but slower.
   ArrayDeque is the recommended modern alternative when thread safety is not required.
*/
